### PR TITLE
Speaker FAQ

### LINKED ISSUE #127: Make a page for FAQ on speakers
Again, this issue is up : https://github.com/speakers-in-tech/conference-data/issues/5

What would be interesting for everyone, is to clarify our position with speakers, on a page, with the process for talk selection, video processing, travel costs, ...  (FAQ - Speakers).

### PR DESCRIPTION
**Pull request by iusildra**
Fixes #127

### CODE REVIEW

**Comment by ahoy-jon** [comment]
@iusildra 

Every reviewer emits a note on each talk and the talks are selected based on the average note. The grade is note the only criterion, we also take into account the diversity of the subjects


C'est pas plutôt : 

Reviewer rank talks (between #1 and #5), can ask for precisions if needed. The global rank between talks is used to guide selection during overview in group sessions. We take into account diversity of subjects, and also give some room to "experimental" subjects, first time speakers...

**Comment by iusildra** [comment]
Yep, plus complet et mieux formulé

**Comment by ahoy-jon** [comment]
Tu peux rajouter à côté (en petit ou autre) 

"there is a strated, open ballot, exponentially weighted borda count to help with pre-selection"

**Comment by ahoy-jon** [comment]
Maintenant, il faudrait rajouter la partie, et trouver un moyen de lui faire un permalien.


Do I need to sign something? 

When your talk is selected, you just need to confirm you are willing to given your talk, and we send you a form about travel and expenses, and keep you updated when we announce your talk.

et d'autres cas si tu as le courage de cadrer ça : 

Couple of situations:

if I am not selected?
You receive a coupon for tickets.

if I am selected and I already bought conference tickets?
You are reimbursed

**Comment by iusildra** [comment]
pourquoi faire un permalien ? Si on le laisse sur la page de la FAQ ça ne va pas bouger d'une année à l'autre ?

**Comment by ahoy-jon** [comment]
Pour pouvoir pointer directement vers cette partie !

**Comment by iusildra** [comment]
avec un `https://scala.io/faq#speaker-questions` ça passe ?

**Pull request merged**
